### ISSUE TITLE
Support Spark 2.3

### ISSUE THREAD

**Issue by NJordan72** [harsha2010/magellan#213]
Currently Spark doesn't work with Spark 2.3.

**Comment by milanvdm** [comment]
Same issue here.
We are getting `java.lang.NoSuchMethodError: org.apache.spark.sql.catalyst.expressions.codegen.CodegenContext.addMutableState(Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;)` when using 

```
val checkIsInCountry = udf { (point: Point, countryPolygons: Seq[Polygon]) =>
        countryPolygons.exists(p => {
          // Consider points that are explicitly contained in the shapes or to have some tolerance also consider those that are in the bounding boxes
          p.contains(point) || (
            point.getX() >= p.boundingBox.getXmin() && point.getX() <= p.boundingBox.getXmax() &&
            point.getY() >= p.boundingBox.getYmin() && point.getY() <= p.boundingBox.getYmax())
        })
      }
```

**Comment by NJordan72** [comment]
@harsha2010 You mentioned in Gitter that you had a PR that would enable Spark 2.3 support.  Is that something you can push?  I've done some work to try to get it to work, but there is at least one test failing based on my branch.  Happy to push that here as well if that is easier to work off of.

**Comment by geoHeil** [comment]
On HDP 2.6.4 spark 2.2 I get `java.lang.NoSuchMethodError: org.apache.spark.sql.catalyst.expressions.codegen.CodegenContext.addMutableState(Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;)V` This looks pretty familiar to https://github.com/typelevel/frameless/issues/262 Are there any news regarding 2.3 support?

**Comment by NJordan72** [comment]
Closed
