### ISSUE TITLE
Project compatible with spark 1.6.1???

### ISSUE THREAD

**Issue by SrinivasRIL** [harsha2010/magellan#98]
Hi @harsha2010 ,
I wanted to know if the project is compatible with spark 1.6.1 or not?
 I am pretty new to spark and want to do geospatial analytics using spark in our organisation. I have spark installed , but somehow I am not able to figure out how to add magellan and use it. I have gitcloned the package and I tried invoking the spark-shell using the same command. but it says harsha2010#magellan;1.0.4-s_2.11: not found
 If someone could demonstrate the initial steps before invoking the spark-shell command, it would be great and I could proceed with some analysis. 

Expecting a reply soon.

Thanks

**Comment by SrinivasRIL** [comment]
Hi @harsha2010 

I have already mentioned that I have spark 1.6.1

I installed magellan-1.0.4-s_2.11.jar  and did  a spark-shell --jars magellan-1.0.4-s_2.11.jar  .

However when i try to import a magellancontext 
import org.apache.spark.sql.magellan.MagellanContext

I get the following error
<console>:25: error: object MagellanContext is not a member of package org.apache.spark.sql.magellan
         import org.apache.spark.sql.magellan.MagellanContext.

I am not sure this is because of compatibility issues with spark 1.6.1 but any insight would be helpful...

Expecting someone to reply soon.


Thanks

**Comment by harsha2010** [comment]
1.0.4 works with spark 2.1+
also, you don;t need to import MagellanContext anymore

For Spark 1.6, you can download the release tagged 1.6 and build it using sbt/sbt clean test spDist
