### ISSUE TITLE
Runtime issue running with spark 1.6

### ISSUE THREAD

**Issue by INRIX-Trang-Nguyen** [harsha2010/magellan#53]
Could you tell me if magellan is compatible with spark 1.6?

I am running into this issue trying to convert a parsed RDD to DF:

case class Trip(trip_id: String,
                  probe_id: String,
                  provider_id: String,
                  start_time: Date,
                  start_hour: Integer,
                  start_point: Point,
                  trip_mean_speed: Double,
                  trip_distance_m: Double
                   )
import sqlContext.implicits._
    val tripDF = tripSource.loadMovingTrips(processingDay, sourceUrl).toDF()

Error: Exception in thread "main" java.lang.NoSuchMethodError: scala.reflect.api.JavaUniverse.runtimeMirror(Ljava/lang/ClassLoader;)Lscala/reflect/api/JavaUniverse$JavaMirror;

Thanks,
Trang

**Comment by harsha2010** [comment]
@INRIX-Trang-Nguyen , magellan is not compatible with Spark 1.6
I am working on a release that is compatible with Spark 1.6 but since Spark 1.6 introduces a lot of changes that affect Magellan;s performance, it is turning out to be a slower upgrade than i anticipated.. look for a release in the next month

**Comment by INRIX-Trang-Nguyen** [comment]
Thanks. Is it still possible to use 1.6 with just rdds, or  will that break as well?

Trang

**Comment by INRIX-Trang-Nguyen** [comment]
Also, does it work with 1.5?

From: Trang Nguyen
Sent: Friday, February 12, 2016 12:53 PM
To: 'harsha2010/magellan' <reply@reply.github.com>; harsha2010/magellan <magellan@noreply.github.com>
Subject: RE: [magellan] Runtime issue running with spark 1.6 (#53)

Thanks. Is it still possible to use 1.6 with just rdds, or  will that break as well?

Trang

**Comment by cris-pin** [comment]
Hi there harsha2010, I wondered if you had got any further with 1.6 support and just wanted to say thank-you for such excellent work so far! Kind regards
