### ISSUE TITLE
Sample code not working in V1.0.4-s_2.11

### ISSUE THREAD

**Issue by nyitzkj1992** [harsha2010/magellan#100]
Hi Harsha,

I am now using Scala 2.11.8 and Spark 2.1.0

So I use Magellan 1.0.4-s_2.11

But when I want to run:
 case class PolygonRecord(polygon:polygon)
it has the error:
:11: error: not found: type Polygon

And when I want to import
import org.apache.spark.sql.magellan.MagellanContext
It generates error:
 error: object magellanContext is not a member of package org.apache.spark.sql.magellan

Could you help me

Thank you

**Comment by harsha2010** [comment]
did you include the following import ?
import magellan.Polygon

Also, starting Magellan 1.0.4 there is no MagellanContext. Please drop that import.

**Comment by nyitzkj1992** [comment]
Hi Ram,

Thank you for your response.

I actually used :
import magellan.{Point, Polygon, PolyLine}

Does  this have any difference to "import magellan.Polygon"

Also, I cannot use Point type either.

The Scala is v2.11.8 and Spark is V2.1.0

Thank you,

Jay

**Comment by nyitzkj1992** [comment]
[image: Inline image 1]
Attached is the screenshot
Thank you

**Comment by nyitzkj1992** [comment]
![capture](https://cloud.githubusercontent.com/assets/26145046/23525853/e7df6a56-ff5d-11e6-843c-4be9d161face.JPG)
Attached is the error message, thank you

**Comment by harsha2010** [comment]
@nyitzkj1992 this is weird. it might have something to do with how the spark repl interacts with case classes in Scala 2.11
This seems to work fine on a Databricks notebook.
https://databricks-prod-cloudfront.cloud.databricks.com/public/4027ec902e239c93eaaa8714f173bcfc/137058993011870/882779309834027/6891974485343070/latest.html

A workaround on the repl could be to not define case classes but use tuples instead?
for example, instead of PolygonRecord(..) use Tuple2[Polygon, Int] and then use session.implicits._ to implicitly convert product classes into DF

**Comment by nyitzkj1992** [comment]
Thank you Ram.

I am still confused.

So does this mean v1.0.4 cannot work fine with Spark 2.1 or Scala 2.11？

Thank you

**Comment by harsha2010** [comment]
it works just fine with Spark 2.1 and Scala 2.11

**Comment by harsha2010** [comment]
I just double checked by creating a simple class and invoking it within Spark 2.1 that this problem exists outside of Magellan.. for some reason, the spark repl seems to not recognize case classes if they are referring to complex types defined outside the repl. need to dig into this more, but this is not a Magellan specific problem

**Comment by nyitzkj1992** [comment]
Thank you Ram！If you have any update，please let me know. 

Best，
Jay

**Comment by nyitzkj1992** [comment]
Hi Ram.

I find a similar issue from others.
http://stackoverflow.com/questions/42517197/spark-reduce-by-key-doesnt-work-in-repl-for-case-class-from-jar
It looks like this is a Spark2.1 problem. 

Thank you

**Comment by harsha2010** [comment]
Thanks for researching this! I'm going to close this issue as its not a Magellan bug. You can use workarounds like creating case classes outside of the REPL (or using Tuples)
