### ISSUE TITLE
spark-shell example not working

### ISSUE THREAD

**Issue by INRIX-Trang-Nguyen** [harsha2010/magellan#54]
Hi,

When I try to run through the examples on the wiki in spark-shell of Spark 1.5 (prebuilt with Hadoop 1.4), I am getting the following errors:
scala> val points = sc.parallelize(Seq((-1.0, -1.0), (-1.0, 1.0), (1.0, -1.0))).toDF("x", "y").select(point($"x", $"y").as("point"))
points: org.apache.spark.sql.DataFrame = [point: poin]

scala> 

scala> points.show()
16/02/12 18:06:34 ERROR Executor: Exception in task 0.0 in stage 0.0 (TID 0)
java.lang.AbstractMethodError: org.apache.spark.sql.catalyst.expressions.Expression.genCode(Lorg/apache/spark/sql/catalyst/expressions/codegen/CodeGenContext;Lorg/apache/spark/sql/catalyst/expressions/codegen/GeneratedExpressionCode;)Ljava/lang/String;
	at org.apache.spark.sql.catalyst.expressions.Expression.gen(Expression.scala:98)
	at org.apache.spark.sql.catalyst.expressions.codegen.GenerateMutableProjection$$anonfun$1.apply(GenerateMutableProjection.scala:46)
	at org.apache.spark.sql.catalyst.expressions.codegen.GenerateMutableProjection$$anonfun$1.apply(GenerateMutableProjection.scala:43)
	at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:244)
	at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:244)
	at scala.collection.mutable.ResizableArray$class.foreach(ResizableArray.scala:59)

Is the support for Spark 1.5 not yet available? I see a related topic in the issues list but wasn't sure whether that has been resolved.

Thanks,
Trang

**Comment by harsha2010** [comment]
@INRIX-Trang-Nguyen yes spark 1.5 and 1.6 support is not there yet..
We will skip Spark 1.5 support and directly go to Spark 1.6 since there have been some fundamental changes introduced by tungsten/ codegen in Spark 1.6 which makes 1.5 support not worth the rewrite on our side

**Comment by INRIX-Trang-Nguyen** [comment]
Thanks the above example does work with 1.4. My logic (similar implementation) works in the spark-shell but runs into a runtime error when submitting a job:
 import sqlContext.implicits._
    val trips = tripSource.loadMovingTrips(processingDay, sourceUrl).toDF
    trips.show()

Error when executed as a job:
6/02/12 21:02:08 INFO SparkContext: Created broadcast 2 from map at TripSource.scala:50
Exception in thread "main" java.lang.NoSuchMethodError: scala.reflect.api.JavaUniverse.runtimeMirror(Ljava/lang/ClassLoader;)Lscala/reflect/api/JavaUniverse$JavaMirror;
	at com.inrix.analytics.trip.metrics.TripMetricsApp$.main(TripMetricsApp.scala:48)
	at com.inrix.analytics.trip.metrics.TripMetricsApp.main(TripMetricsApp.scala)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	

Same logic in spark-shell is fine:

trips.show()
6/02/12 20:56:44 INFO DAGScheduler: Job 3 finished: show at <console>:43, took 0.407791 s
+--------------------+--------------------+
|             trip_id|         start_point|
+--------------------+--------------------+
|c95d63124d8c9e38f...|Point(-77.1861814...|
|a6d97c525e5016c72...|Point(-77.0432135...|
|ef22b7424ea94f27c...|Point(-77.0580354...|
|bb04459825a1de60f...|Point(-48.702702,...|
+--------------------+--------------------+

Any idea why?

Thanks,
Trang

**Comment by INRIX-Trang-Nguyen** [comment]
Found the reason - I was using a newer version of the scala compiler (2.11). Works with scala 2.10.4.

**Comment by kaxil** [comment]
Doesn't work for scala 2.10.5 & spark 1.6 as well. I get a `java.lang.AbstractMethodError` error when I try to run `points.show()`. Any solutions please  @harsha2010  ?
